export const FORECAST = {
  FETCH: {
    REQUEST: 'FORECAST.FETCH.REQUEST',
    SUCCESS: 'FORECAST.FETCH.SUCCESS',
    ERROR: 'FORECAST.FETCH.ERROR'
  },
  ERROR: {
    CLEAR: 'FORECAST.ERROR.CLEAR'
  },
  CLEAR_STATE: 'FORECAST.CLEAR_STATE'
};
